### ISSUE TITLE
Scaffold is broken out of the box

### ISSUE THREAD

**Issue by ttbarnes** [banderson/generator-redux#34]
- `yo redux`
- respond to the 4 questions

Immediately get an error (with or without installing dependencies). Nothing scaffolded.

```
? Install dependencies? No
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at deps (/usr/local/lib/node_modules/generator-redux/generators/app/index.js:119:12)
    at /usr/local/lib/node_modules/generator-redux/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by gcoonrod** [comment]
Seeing this same error with Node v4.2.1

**Comment by tomenden** [comment]
I am also getting this error, Node v4.2.0

**Comment by banderson** [comment]
@ttbarnes @gcoonrod @tomenden I just pushed a fix in v0.3.3 that may have fixed this. I confirmed that it works on my machine using node 4.2.1 as well as 5.x.

**Comment by ttbarnes** [comment]
Thanks @banderson , the scaffold is working great from here now with node v5.1.0.

**Comment by jmfirth** [comment]
Works great on node v5.3.0
